---
version: "3"
services:
  master:
    build: dockerfiles/jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-master:/var/jenkins_home
      - jenkins-shared:/tmp/jenkins_shared
  buildenv-curl:
    build: dockerfiles/buildenv-curl
    container_name: buildenv-curl
    volumes:
      - jenkins-shared:/tmp/jenkins_shared
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    container_name: artifactory
    ports:
      - 8081:8081
      - 8082:8082
    volumes:
      - /var/artifactory_home:/var/opt/jfrog/artifactory
#  sonarqube:
#    image: sonarqube
#    container_name: sonarqube
#    ports:
#      - "9000:9000"
#    volumes:
#      - sonarqube-conf:/opt/sonarqube/conf
#      - sonarqube-data:/opt/sonarqube/data
#      - sonarqube-logs:/opt/sonarqube/logs
#      - sonarqube-extensions:/opt/sonarqube/extensions

volumes:
  jenkins-shared:
  jenkins-master:
#  sonarqube-conf:
#  sonarqube-data:
#  sonarqube-logs:
#  sonarqube-extensions:
